---
title: "NM2207 Final Project"
---

**Taylor Swift: A Data Story (not a love story)**

Taylor Swift has largely been a very successful artist, even in the modern day. In August 2023, Taylor Swift was the first female artist to reach 100 million monthly listeners. In fact, Swift has a whopping \$740 million net worth as of June 2023 (according to Forbes).

What makes her music so popular? And how has her music changed and evolved over time? Analysing the statistics of Swift's music, from this data collected from 274 of her tracks, will help other musicians to figure out the ingredients in her music to cook up hits just like her. Maybe even you, following her recipe, will be able to catapult yourself to stardom!

**I. Shake if off, Shake it off!**

How energetic is Taylor Swift's music?

Surely, everyone has bopped around to her hits at least once or twice before. But has her music become more danceable to, or has it become slower and more melancholic?

To find out, I plotted a graph of the following variables: Danceability, energy and tempo against the release dates of her music! This will allow us to see if Swift's music has become more energetic or slower and more melancholic over the years.

Insert graph of danceability, energy and tempo against release_date <iframe height="500" width="100%" frameborder="no" src="https://jav521.shinyapps.io/TaylorSongs/"> </iframe>

Did you know? Taylor Swift's most danceable song is "I Think He Knows", released in August 2019 with a danceability score of 0.897!

Whereas, her least danceable song is The Archer, with a Spotify danceability score of 0.292. Guess she didn't quite hit the mark on that one...

**II. Frequency Profiles: So it's gonna be forever? (Or it's gonna go down in flames)**

Let's use a histogram to find out what Taylor Swift's music is like!

<iframe height="500" width="100%" frameborder="no" src="https://jav521.shinyapps.io/Hello_Taylor/">

</iframe>

As you can see, Taylor Swift has had a diverse number of tracks, all with varying tempos, energy, loudness etc.

However, there are some statistics in which she scores particularly lower/higher on, for example, speechiness, which determines the presence of spoken words in a track. Taylor Swift had a relatively low speechiness score, with a mean of 0.0533. Perhaps, one of the reasons why Swift is so successful is her ability to create songs that mostly contain intricate melodies, rather than using speech or spoken words to embellish her songs.

Ironically, a lot of her songs are not acoustic either. Although she does have a few acoustic versions of her songs, she has many songs that score low in the acoustic department, with a mean acousticness score of 0.300. Maybe her use of electric and digital instruments in appropriate scenarios could be what sets her apart from other singer-songwriters. Taylor Swift also did not have many live recorded tracks, showing how most of her tracks are meticulously prerecorded, with a mean liveness score of 0.141.

Her overall instrumentalness is also quite low, with a mean instrumentalness of 0.00366. This goes to show that vocals make up a huge part of her music, and she isn't afraid to show off her vocal prowess!

**III. Give me the keys**

Let's find out what Taylor Swift's favourite key signature is!

Insert Graph of key_mode against track_name <iframe height="500" width="100%" frameborder="no" src="https://jav521.shinyapps.io/Taylor_Key/"> </iframe>

-   Taylor's top 3 favourite keys are: G Major (n=50), C Major (n=41), F Major (n=30).

-   She had 11 songs with no clear key.

-   She had no songs in A# Minor, D Minor, F# Minor, G# Minor. That's a minor inconvenience!

**Conclusion**

At the start, I started this project to figure out what was Taylor Swift's recipe for success. But looking at the data, one thing is clear. Swift did not get successful with any particular recipe, but she created many diverse songs with different tempos, keys, and moods, in her own single signature style and voice that has never changed throughout the years. So to all you budding musicians, perhaps it isn't so important what key you use, whether you use acoustic instruments or whether you have a certain tempo, but rather, about having your individual style and sticking to it!

That being said, for those who want to follow in Taylor Swift's footsteps, there are a few things that you can do. Start by making more melodies within your music and less speech, use more electronic instruments rather than acoustic ones, and keep honing your vocal skills to make more use of them rather than instrumentation!
